export const initialRecordsRecords = [{
  _id: '6498facfc0e0eca045a438d5',
  operation_id: '6498faadcfb5d4f39d4fb8a9',
  user_id: '6498faa6c8b7ab0fdd68cea5',
  amount: 2,
  user_balance: 2,
  user_input_numbers: [
    2,
    2,
  ],
  operation_response: '4',
  status: 'active',
  date: '2023-06-26T02:41:19.621Z',
  __v: 0,
  id: '6498facfc0e0eca045a438d5',
},
{
  _id: '64990008cb2402fa49c05478',
  operation_id: '6498faadcfb5d4f39d4fb8a9',
  user_id: '6498faa6c8b7ab0fdd68cea5',
  amount: 2,
  user_balance: 2,
  user_input_numbers: [
    2,
    2,
  ],
  operation_response: '4',
  status: 'active',
  date: '2023-06-26T03:03:36.284Z',
  __v: 0,
  id: '64990008cb2402fa49c05478',
},
{
  _id: '6499000acb2402fa49c0547e',
  operation_id: '6498faadcfb5d4f39d4fb8a9',
  user_id: '6498faa6c8b7ab0fdd68cea5',
  amount: 2,
  user_balance: 2,
  user_input_numbers: [
    2,
    2,
  ],
  operation_response: '4',
  status: 'active',
  date: '2023-06-26T03:03:38.019Z',
  __v: 0,
  id: '6499000acb2402fa49c0547e',
},
{
  _id: '6499000bcb2402fa49c05480',
  operation_id: '6498faadcfb5d4f39d4fb8a9',
  user_id: '6498faa6c8b7ab0fdd68cea5',
  amount: 2,
  user_balance: 2,
  user_input_numbers: [
    2,
    2,
  ],
  operation_response: '4',
  status: 'active',
  date: '2023-06-26T03:03:39.325Z',
  __v: 0,
  id: '6499000bcb2402fa49c05480',
},
{
  _id: '6499000ccb2402fa49c05482',
  operation_id: '6498faadcfb5d4f39d4fb8a9',
  user_id: '6498faa6c8b7ab0fdd68cea5',
  amount: 2,
  user_balance: 2,
  user_input_numbers: [
    2,
    2,
  ],
  operation_response: '4',
  status: 'active',
  date: '2023-06-26T03:03:40.634Z',
  __v: 0,
  id: '6499000ccb2402fa49c05482',
},
{
  _id: '6499000dcb2402fa49c05484',
  operation_id: '6498faadcfb5d4f39d4fb8a9',
  user_id: '6498faa6c8b7ab0fdd68cea5',
  amount: 2,
  user_balance: 2,
  user_input_numbers: [
    2,
    2,
  ],
  operation_response: '4',
  status: 'active',
  date: '2023-06-26T03:03:41.893Z',
  __v: 0,
  id: '6499000dcb2402fa49c05484',
},
{
  _id: '6499000fcb2402fa49c05486',
  operation_id: '6498faadcfb5d4f39d4fb8a9',
  user_id: '6498faa6c8b7ab0fdd68cea5',
  amount: 2,
  user_balance: 2,
  user_input_numbers: [
    2,
    2,
  ],
  operation_response: '4',
  status: 'active',
  date: '2023-06-26T03:03:43.095Z',
  __v: 0,
  id: '6499000fcb2402fa49c05486',
}];

export const createRecordType = 'division';
export const createRecordType2 = 'multiplication';
export const createRecordType3 = 'square_root';

export const createRecord = {
  _id: '6498fba26c94b7f12a4323d0',
  operation_id: '6498faadcfb5d4f39d4fb8a9',
  user_id: '6498faa6c8b7ab0fdd68cea5',
  amount: 2,
  user_balance: 2,
  user_input_numbers: [
    2,
    2,
  ],
  operation_response: '4',
  status: 'active',
  date: '2023-06-26T03:03:43.095Z',
  __v: 0,
  id: '6498fba26c94b7f12a4323d0',
};

export const createRecord2 = {
  _id: '6498fba76c94b7f12a4323d6',
  operation_id: '6498faadcfb5d4f39d4fb8a9',
  user_id: '6498faa6c8b7ab0fdd68cea5',
  amount: 2,
  user_balance: 2,
  user_input_numbers: [
    2,
    2,
  ],
  operation_response: '4',
  status: 'active',
  date: '2023-06-26T03:03:43.095Z',
  id: '6498fba76c94b7f12a4323d6',
};

export const createRecord3 = {
  _id: '6498fbb16c94b7f12a4323da',
  operation_id: '6498faadcfb5d4f39d4fb8a9',
  user_id: '6498faa6c8b7ab0fdd68cea5',
  amount: 2,
  user_balance: 2,
  user_input_numbers: [
    2,
    2,
  ],
  operation_response: '4',
  status: 'active',
  date: '2023-06-26T03:03:43.095Z',
  __v: 0,
  id: '6498fbb16c94b7f12a4323da',
};

// eslint-disable-next-line no-useless-escape
export const createRecordErrorString = `E11000 duplicate key error collection: arithmetic-calculator-api.records index: type_1 dup key: { type: \"${createRecordType}\" }`;
// eslint-disable-next-line no-useless-escape
export const updateRecordErrorString = `E11000 duplicate key error collection: arithmetic-calculator-api.records index: type_1 dup key: { type: \"${createRecordType}\" }`; //

export const recordCreateRecordString = JSON.stringify(createRecord);
export const recordCreateRecord2String = JSON.stringify(createRecord2);
export const recordCreateRecord3String = JSON.stringify(createRecord3);

export const eventCreateRecord = {
  body: recordCreateRecordString,
  headers: {
    'Content-Type': 'application/json',
    'Record-Agent': 'PostmanRuntime/7.29.2',
    Accept: '*/*',
    'Postman-Token': '685b9667-31d0-4552-bd2c-10bba79a5b90',
    Host: 'localhost:3000',
    'Accept-Encoding': 'gzip, deflate, br',
    Connection: 'keep-alive',
    'Content-Length': '93',
    Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ5ZTQ5YzI1YTNiY2ZlOTkyMGQwMmU1IiwidXNlcm5hbWUiOiJ3ZWIyc29sdWNvZXNAZ21haWwuY29tIiwiaWF0IjoxNjg4MTYzNDg3LCJleHAiOjE2ODgxNjcwODd9._wB4xETbN-d8iUELQyEW-SBW3WVRmsaVNeaaZTTjj5E',
  },
  httpMethod: 'POST',
  isBase64Encoded: false,
  multiValueHeaders: {
    'Content-Type': ['application/json'],
    'Record-Agent': ['PostmanRuntime/7.29.2'],
    Accept: ['*/*'],
    'Postman-Token': ['685b9667-31d0-4552-bd2c-10bba79a5b90'],
    Host: ['localhost:3000'],
    'Accept-Encoding': ['gzip, deflate, br'],
    Connection: ['keep-alive'],
    'Content-Length': ['93'],
  },
  multiValueQueryStringParameters: null,
  path: '/records',
  pathParameters: null,
  queryStringParameters: null,
  requestContext: {
    accountId: 'offlineContext_accountId',
    apiId: 'offlineContext_apiId',
    authorizer: {
      claims: undefined,
      principalId: 'offlineContext_authorizer_principalId',
      scopes: undefined,
    },
    domainName: 'offlineContext_domainName',
    domainPrefix: 'offlineContext_domainPrefix',
    extendedRequestId: '7df0babb-5826-4c99-9f3b-543aa8fb4e1a',
    httpMethod: 'POST',
    identity: {
      accessKey: null,
      accountId: 'offlineContext_accountId',
      apiKey: 'offlineContext_apiKey',
      apiKeyId: 'offlineContext_apiKeyId',
      caller: 'offlineContext_caller',
      cognitoAuthenticationProvider: 'offlineContext_cognitoAuthenticationProvider',
      cognitoAuthenticationType: 'offlineContext_cognitoAuthenticationType',
      cognitoIdentityId: 'offlineContext_cognitoIdentityId',
      cognitoIdentityPoolId: 'offlineContext_cognitoIdentityPoolId',
      principalOrgId: null,
      sourceIp: '127.0.0.1',
      record: 'offlineContext_record',
      recordAgent: 'PostmanRuntime/7.29.2',
      recordArn: 'offlineContext_recordArn',
    },
    recordName: undefined,
    path: '/records',
    protocol: 'HTTP/1.1',
    requestId: '0d890b2b-f2be-43ee-8559-db9f37b1b616',
    requestTime: '26/Jun/2023:01:04:14 -0300',
    requestTimeEpoch: 1687752254757,
    resourceId: 'offlineContext_resourceId',
    resourcePath: '/dev/records',
    stage: 'dev',
  },
  resource: '/records',
  stageVariables: null,
};

export const eventUpdateRecordAmount = {
  body: JSON.stringify({
    amount: 3,
  }),
  headers: {
    'Content-Type': 'application/json',
    'Record-Agent': 'PostmanRuntime/7.29.2',
    Accept: '*/*',
    'Postman-Token': '685b9667-31d0-4552-bd2c-10bba79a5b90',
    Host: 'localhost:3000',
    'Accept-Encoding': 'gzip, deflate, br',
    Connection: 'keep-alive',
    'Content-Length': '93',
    Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ5ZTQ5YzI1YTNiY2ZlOTkyMGQwMmU1IiwidXNlcm5hbWUiOiJ3ZWIyc29sdWNvZXNAZ21haWwuY29tIiwiaWF0IjoxNjg4MTYzNDg3LCJleHAiOjE2ODgxNjcwODd9._wB4xETbN-d8iUELQyEW-SBW3WVRmsaVNeaaZTTjj5E',
  },
  httpMethod: 'POST',
  isBase64Encoded: false,
  multiValueHeaders: {
    'Content-Type': ['application/json'],
    'Record-Agent': ['PostmanRuntime/7.29.2'],
    Accept: ['*/*'],
    'Postman-Token': ['685b9667-31d0-4552-bd2c-10bba79a5b90'],
    Host: ['localhost:3000'],
    'Accept-Encoding': ['gzip, deflate, br'],
    Connection: ['keep-alive'],
    'Content-Length': ['93'],
  },
  multiValueQueryStringParameters: null,
  path: '/records',
  pathParameters: {
    // eslint-disable-next-line no-underscore-dangle
    id: createRecord._id,
  },
  queryStringParameters: null,
  requestContext: {
    accountId: 'offlineContext_accountId',
    apiId: 'offlineContext_apiId',
    authorizer: {
      claims: undefined,
      principalId: 'offlineContext_authorizer_principalId',
      scopes: undefined,
    },
    domainName: 'offlineContext_domainName',
    domainPrefix: 'offlineContext_domainPrefix',
    extendedRequestId: '7df0babb-5826-4c99-9f3b-543aa8fb4e1a',
    httpMethod: 'POST',
    identity: {
      accessKey: null,
      accountId: 'offlineContext_accountId',
      apiKey: 'offlineContext_apiKey',
      apiKeyId: 'offlineContext_apiKeyId',
      caller: 'offlineContext_caller',
      cognitoAuthenticationProvider: 'offlineContext_cognitoAuthenticationProvider',
      cognitoAuthenticationType: 'offlineContext_cognitoAuthenticationType',
      cognitoIdentityId: 'offlineContext_cognitoIdentityId',
      cognitoIdentityPoolId: 'offlineContext_cognitoIdentityPoolId',
      principalOrgId: null,
      sourceIp: '127.0.0.1',
      record: 'offlineContext_record',
      recordAgent: 'PostmanRuntime/7.29.2',
      recordArn: 'offlineContext_recordArn',
    },
    recordName: undefined,
    path: '/records',
    protocol: 'HTTP/1.1',
    requestId: '0d890b2b-f2be-43ee-8559-db9f37b1b616',
    requestTime: '26/Jun/2023:01:04:14 -0300',
    requestTimeEpoch: 1687752254757,
    resourceId: 'offlineContext_resourceId',
    resourcePath: '/dev/records',
    stage: 'dev',
  },
  resource: '/records',
  stageVariables: null,
};

export const eventUpdateRecordRecordname = {
  body: JSON.stringify({
    type: Math.random() + createRecordType,
  }),
  headers: {
    'Content-Type': 'application/json',
    'Record-Agent': 'PostmanRuntime/7.29.2',
    Accept: '*/*',
    'Postman-Token': '685b9667-31d0-4552-bd2c-10bba79a5b90',
    Host: 'localhost:3000',
    'Accept-Encoding': 'gzip, deflate, br',
    Connection: 'keep-alive',
    'Content-Length': '93',
    Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ5ZTQ5YzI1YTNiY2ZlOTkyMGQwMmU1IiwidXNlcm5hbWUiOiJ3ZWIyc29sdWNvZXNAZ21haWwuY29tIiwiaWF0IjoxNjg4MTYzNDg3LCJleHAiOjE2ODgxNjcwODd9._wB4xETbN-d8iUELQyEW-SBW3WVRmsaVNeaaZTTjj5E',
  },
  httpMethod: 'POST',
  isBase64Encoded: false,
  multiValueHeaders: {
    'Content-Type': ['application/json'],
    'Record-Agent': ['PostmanRuntime/7.29.2'],
    Accept: ['*/*'],
    'Postman-Token': ['685b9667-31d0-4552-bd2c-10bba79a5b90'],
    Host: ['localhost:3000'],
    'Accept-Encoding': ['gzip, deflate, br'],
    Connection: ['keep-alive'],
    'Content-Length': ['93'],
  },
  multiValueQueryStringParameters: null,
  path: '/records',
  pathParameters: {
    // eslint-disable-next-line no-underscore-dangle
    id: createRecord._id,
  },
  queryStringParameters: null,
  requestContext: {
    accountId: 'offlineContext_accountId',
    apiId: 'offlineContext_apiId',
    authorizer: {
      claims: undefined,
      principalId: 'offlineContext_authorizer_principalId',
      scopes: undefined,
    },
    domainName: 'offlineContext_domainName',
    domainPrefix: 'offlineContext_domainPrefix',
    extendedRequestId: '7df0babb-5826-4c99-9f3b-543aa8fb4e1a',
    httpMethod: 'POST',
    identity: {
      accessKey: null,
      accountId: 'offlineContext_accountId',
      apiKey: 'offlineContext_apiKey',
      apiKeyId: 'offlineContext_apiKeyId',
      caller: 'offlineContext_caller',
      cognitoAuthenticationProvider: 'offlineContext_cognitoAuthenticationProvider',
      cognitoAuthenticationType: 'offlineContext_cognitoAuthenticationType',
      cognitoIdentityId: 'offlineContext_cognitoIdentityId',
      cognitoIdentityPoolId: 'offlineContext_cognitoIdentityPoolId',
      principalOrgId: null,
      sourceIp: '127.0.0.1',
      record: 'offlineContext_record',
      recordAgent: 'PostmanRuntime/7.29.2',
      recordArn: 'offlineContext_recordArn',
    },
    recordName: undefined,
    path: '/records',
    protocol: 'HTTP/1.1',
    requestId: '0d890b2b-f2be-43ee-8559-db9f37b1b616',
    requestTime: '26/Jun/2023:01:04:14 -0300',
    requestTimeEpoch: 1687752254757,
    resourceId: 'offlineContext_resourceId',
    resourcePath: '/dev/records',
    stage: 'dev',
  },
  resource: '/records',
  stageVariables: null,
};

export const eventUpdateExistingRecordRecordname = {
  body: JSON.stringify({
    type: createRecordType,
  }),
  headers: {
    'Content-Type': 'application/json',
    'Record-Agent': 'PostmanRuntime/7.29.2',
    Accept: '*/*',
    'Postman-Token': '685b9667-31d0-4552-bd2c-10bba79a5b90',
    Host: 'localhost:3000',
    'Accept-Encoding': 'gzip, deflate, br',
    Connection: 'keep-alive',
    'Content-Length': '93',
    Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ5ZTQ5YzI1YTNiY2ZlOTkyMGQwMmU1IiwidXNlcm5hbWUiOiJ3ZWIyc29sdWNvZXNAZ21haWwuY29tIiwiaWF0IjoxNjg4MTYzNDg3LCJleHAiOjE2ODgxNjcwODd9._wB4xETbN-d8iUELQyEW-SBW3WVRmsaVNeaaZTTjj5E',
  },
  httpMethod: 'POST',
  isBase64Encoded: false,
  multiValueHeaders: {
    'Content-Type': ['application/json'],
    'Record-Agent': ['PostmanRuntime/7.29.2'],
    Accept: ['*/*'],
    'Postman-Token': ['685b9667-31d0-4552-bd2c-10bba79a5b90'],
    Host: ['localhost:3000'],
    'Accept-Encoding': ['gzip, deflate, br'],
    Connection: ['keep-alive'],
    'Content-Length': ['93'],
  },
  multiValueQueryStringParameters: null,
  path: '/records',
  pathParameters: {
    // eslint-disable-next-line no-underscore-dangle
    id: createRecord._id,
  },
  queryStringParameters: null,
  requestContext: {
    accountId: 'offlineContext_accountId',
    apiId: 'offlineContext_apiId',
    authorizer: {
      claims: undefined,
      principalId: 'offlineContext_authorizer_principalId',
      scopes: undefined,
    },
    domainName: 'offlineContext_domainName',
    domainPrefix: 'offlineContext_domainPrefix',
    extendedRequestId: '7df0babb-5826-4c99-9f3b-543aa8fb4e1a',
    httpMethod: 'POST',
    identity: {
      accessKey: null,
      accountId: 'offlineContext_accountId',
      apiKey: 'offlineContext_apiKey',
      apiKeyId: 'offlineContext_apiKeyId',
      caller: 'offlineContext_caller',
      cognitoAuthenticationProvider: 'offlineContext_cognitoAuthenticationProvider',
      cognitoAuthenticationType: 'offlineContext_cognitoAuthenticationType',
      cognitoIdentityId: 'offlineContext_cognitoIdentityId',
      cognitoIdentityPoolId: 'offlineContext_cognitoIdentityPoolId',
      principalOrgId: null,
      sourceIp: '127.0.0.1',
      record: 'offlineContext_record',
      recordAgent: 'PostmanRuntime/7.29.2',
      recordArn: 'offlineContext_recordArn',
    },
    recordName: undefined,
    path: '/records',
    protocol: 'HTTP/1.1',
    requestId: '0d890b2b-f2be-43ee-8559-db9f37b1b616',
    requestTime: '26/Jun/2023:01:04:14 -0300',
    requestTimeEpoch: 1687752254757,
    resourceId: 'offlineContext_resourceId',
    resourcePath: '/dev/records',
    stage: 'dev',
  },
  resource: '/records',
  stageVariables: null,
}; // eventUpdateRecordRecordname, eventUpdateExistingRecordRecordname

export const eventFindRecord = {
  body: null,
  headers: {
    'Record-Agent': 'PostmanRuntime/7.29.2',
    Accept: '*/*',
    'Postman-Token': 'e723484d-1e1a-4349-adb1-36abe0ed67bb',
    Host: 'localhost:3000',
    'Accept-Encoding': 'gzip, deflate, br',
    Connection: 'keep-alive',
    Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ5ZTQ5YzI1YTNiY2ZlOTkyMGQwMmU1IiwidXNlcm5hbWUiOiJ3ZWIyc29sdWNvZXNAZ21haWwuY29tIiwiaWF0IjoxNjg4MTYzNDg3LCJleHAiOjE2ODgxNjcwODd9._wB4xETbN-d8iUELQyEW-SBW3WVRmsaVNeaaZTTjj5E',
  },
  httpMethod: 'GET',
  isBase64Encoded: false,
  multiValueHeaders: {
    'Record-Agent': ['PostmanRuntime/7.29.2'],
    Accept: ['*/*'],
    'Postman-Token': ['e723484d-1e1a-4349-adb1-36abe0ed67bb'],
    Host: ['localhost:3000'],
    'Accept-Encoding': ['gzip, deflate, br'],
    Connection: ['keep-alive'],
  },
  multiValueQueryStringParameters: null,
  path: '/records',
  pathParameters: null,
  queryStringParameters: null,
  requestContext: {
    accountId: 'offlineContext_accountId',
    apiId: 'offlineContext_apiId',
    authorizer: {
      claims: undefined,
      principalId: 'offlineContext_authorizer_principalId',
      scopes: undefined,
    },
    domainName: 'offlineContext_domainName',
    domainPrefix: 'offlineContext_domainPrefix',
    extendedRequestId: '1dcd257f-056e-43e7-91ee-0024b68f65cb',
    httpMethod: 'GET',
    identity: {
      accessKey: null,
      accountId: 'offlineContext_accountId',
      apiKey: 'offlineContext_apiKey',
      apiKeyId: 'offlineContext_apiKeyId',
      caller: 'offlineContext_caller',
      cognitoAuthenticationProvider: 'offlineContext_cognitoAuthenticationProvider',
      cognitoAuthenticationType: 'offlineContext_cognitoAuthenticationType',
      cognitoIdentityId: 'offlineContext_cognitoIdentityId',
      cognitoIdentityPoolId: 'offlineContext_cognitoIdentityPoolId',
      principalOrgId: null,
      sourceIp: '127.0.0.1',
      record: 'offlineContext_record',
      recordAgent: 'PostmanRuntime/7.29.2',
      recordArn: 'offlineContext_recordArn',
    },
    recordName: undefined,
    path: '/records',
    protocol: 'HTTP/1.1',
    requestId: '47d229f6-d0eb-493b-bb45-611e58858011',
    requestTime: '26/Jun/2023:16:16:05 -0300',
    requestTimeEpoch: 1687806965911,
    resourceId: 'offlineContext_resourceId',
    resourcePath: '/dev/records',
    stage: 'dev',
  },
  resource: '/records',
  stageVariables: null,
};
