version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.10
        environment:
          - NODE_ENV: "dev"
      - image: circleci/mongo:4.2.0
        port: 27017:27017
        #environment:
        #  - MONGODB_USERNAME: "myrootuser"
        #  - MONGODB_PASSWORD: "mypassword"
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      #- run:
      #    name: MongoDB Install
      #    command: |
      #      sudo apt-get install -y mongodb
      - run:
          name: Database Setup
          command: "mongodb"
      - run:
          name: Install package json dependencies
          command: npm install
      - run:
          name: Run test
          command: npm test